config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos/list'
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'editar'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#completed', as: 'completo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def completed
    @todo = Todo.find(params[:id])
    @todo.update(completed:true)
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
    @completados = Todo.where(completed: true)
    @faltantes = Todo.where(completed: false)
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Trello</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to 'Index', todos_path %> </li>
        <li> <%= link_to 'Lista', todos_list_path %> </li>
        <li> <%= link_to 'Crear nuevo', todos_new_path %> </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script
      src="https://code.jquery.com/jquery-3.2.1.js"
      integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
      crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: @todo, local: true) do |f| %>

 <%= f.label :description, 'description' %>
 <%= f.text_field :description %>

 <%= f.label :completed, 'completed' %>
 <%= f.text_field :completed %>

 <%= f.submit :crear %>

<% end %>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<!--
<div class="well">
  <ul>

    <% @todos.each do |todo| %>
    <li> <%= todo.description %>
    <%= todo.completed %> </li>
    <% end %>

  </ul>

</div> -->

<ul>
    <% @todos.each do |todo| %>
    <li class= "well" style="list-style-type:none">
    <%= todo.description %>
    <%= todo.completed %>
    <h6> <%= link_to "Mostrar", todo, method: :get %> </h6>
    <h6> <%= link_to "Editar",  editar_path(todo) %> </h6>
    <h6> <%= link_to "Eliminar", todo, method: :delete %> </h6>
    <h6> <%= link_to "Completar", completo_path(todo), method: :get, class:'btn btn-success' %> </h6>
    <% end %>
    </li>
</ul>


<%= link_to "Crear ToDo", todos_new_path %>

app/views/todos/list.html.erb
<div class="row">

  <div class="col-md-6">
    <h2>NO COMPLETADOS</h2>
    <% @faltantes.each do |ele| %>
      <ul>
        <li> <%= ele.description %> </li>
      </ul>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2>COMPLETADOS</h2>
    <% @completados.each do |ele| %>
      <ul>
        <li> <%= ele.description %> </li>
      </ul>
    <% end %>
  </div>

</div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h3> <%= @todo.description %> </h3>
<h3> <%= @todo.completed %> </h3>
<h3> <%= time_ago_in_words @todo.created_at %> </h3>